Update all-for-one.md
github/securitylab pull request #382
Opened 2021-06-10 17:44 UTC by gagliardetto

This PR is a draft of how I would address the major points of confusion for bug bounty application submitters, and remove obstacles that might discourage and create friction for anyone considering to write and submit a query.

2021-07-22 20:29 UTC, xcorail requested changes
Hey @gagliardetto thanks for this PR

Sorry for all the suggestions, it's a bit messy but TL;DR is
- Move back the CVE requirement up into the Results section
- Move down the social section
- Align the Results section instructions to the CVE requirement

Let's iterate after this first pass, as all the suggestions make the PR difficult to read

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +
Moved to bottom

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +## 5. CVE ID(s)
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +### Instructions ❓
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +### Your answer 👇
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +	1. CVE-20nn-nnnnn
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +	1. CVE-20nn-nnnnn
```suggestion
## 3. Social

### Instructions ❓

Are you planning to discuss your query publicly? (Blog Post, social networks, etc).

**We would love to [help you] spread the word about the good work you are doing.**

### Your answer 👇

- [ ] Yes
- [ ] No
- [ ] Yes, I already have: [link](link)

```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- If the result(s) is **NOT** fixed **nor disclosed**, then you can privately share your result via email to [security@github.com](mailto:security@github.com?subject=[BugBounty]%20Issue%20#000%20usef
```suggestion
- If the result(s) is **NOT YET** fixed **nor disclosed**, and you are still waiting for a CVE, then you can privately share your result via email to [security@github.com](mailto:security@github.com?subject=[BugBounty]%20Issue%20#000%20useful%20result)
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- Even though your query is **out in the wild** (and it's quite trivial to run it against a sizable batch of projects), let's **not make things easy** for anyone wanting to exploit vulnerable project
```suggestion
- Even though the vulnerabilities found by your query might be **out in the wild** (and it's quite trivial to run it against a sizable batch of projects), let's **not make things easy** for anyone wanting to exploit vulnerable projects.
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- We understand that contacting maintainers of all the vulnerable repositories found by your query is a hard and lenghty process, and that's why we will add a bonus if you will do that **for at least
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- We understand that contacting maintainers of all the vulnerable repositories found by your query is a hard and lenghty process, and that's why we will add a bonus if you will do that **for at least
Still under brainstorming whether we transform The Big Slayer to do that. Let's wait until we have more clarity

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- Anyway, we're here for **automating things away** and if you want to leave the heavy lifting of finding and notifying vulnerable repositories' owners to GitHub security bots, that's fine with us.
```suggestion
- We're here for **securing open source at scale** and if your query finds many vulnerable repositories, requiring a big coordinated disclosure, let's discuss and work together.
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- Provide at least one useful result found by your query, on some revision of a real project.
```suggestion
- Provide at least one useful result found by your query, on some revision of a real project, under the form of a list of CVEs.
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +- But in any case, we need proof that you **did your own reaserch** on [real projects], and succeeded in finding at least one **true positive result [through your query]**, proving that is it a **rea
```suggestion
- If for some reason you cannot provide a CVE, but if you can provide evidence that your query found at least one **real security vulnerability** and if you are confident that the pattern can be found in open source projects, please provide these elements.
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +1. Etc.
```suggestion
1. Other information?
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +	- Description: URL to vulnerable code
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +**OR**
```suggestion
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +### Your answer 👇 (select one)
```suggestion
### Your answer 👇 
```

2021-07-22 20:29 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.md
> +
```suggestion
- Existing CVEs that my query would have been able to find if they weren't already fixed:
	1. CVE-20nn-nnnnn

- Vulnerabilities that my query found and then resulted in a CVE:
	1. CVE-20nn-nnnnn	

  **OR**
```

2021-11-08 17:06 UTC, xcorail commented
👋🏾 @gagliardetto 
Note that this PR will need to be closed / revisited after [this one](https://github.com/github/securitylab/pull/468), which is moving the template from classical `.md` template to an issue form

cc @pwntester

2021-11-08 17:12 UTC, gagliardetto commented
Thank you @xcorail !

Sorry, I completely forgot about this one.

2021-11-23 14:28 UTC, closed without merging