port all-for-one template to issue forms
github/securitylab pull request #468
Opened 2021-11-08 10:36 UTC by pwntester

2021-11-08 10:49 UTC, pwntester commented
@xcorail @kevinbackhouse do you know if there is a way to check how the form would look like without merging it? (other than testing it on a different repo)

2021-11-08 13:08 UTC, pwntester commented
oh, nice catch up, I renamed the file but still get no preview button. do you?

2021-11-08 14:46 UTC, kevinbackhouse commented
You need to click here. It's currently complaining about a yaml error.

![Screenshot from 2021-11-08 14-45-48](https://user-images.githubusercontent.com/4358136/140762756-89f9f4d0-8d90-433b-bb47-00013bc9be74.png)

2021-11-08 17:01 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      required: true
I propose to move this section up in the form, as it's a required input. Putting it at the end, after the social media stuff makes it feel like it's a nice to have

2021-11-08 17:02 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      required: true
For example before the `CWE` input

2021-11-08 17:37 UTC, intrigus-lgtm commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      required: true
This is probably an edge-case, but what about queries for unsafe Github Actions?
These queries are not really written for a specific language...

2021-11-08 23:24 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      placeholder: ex. CWE-502: Deserialization of Untrusted Data
```suggestion
      placeholder: "ex. CWE-502: Deserialization of Untrusted Data"
```

2021-11-08 23:24 UTC, xcorail commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      placeholder: ex. CWE-502: Deserialization of Untrusted Data
Attempt to fix the YAML problem

2021-11-10 09:28 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      required: true
Thanks! I think yaml files can only be scanned as part as a JS project currently. If that would change in the future, we should accommodate new first-citizen languages here in the future (Im looking at you Ruby 😄 )

2021-11-10 09:39 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      required: true
Sure, moved it up

2021-11-10 17:03 UTC, xcorail approved these changes

2021-11-18 11:14 UTC, JarLob requested changes

2021-11-18 11:14 UTC, JarLob commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +        Please make sure to carefully read the [bounty program description and conditions](https://securitylab.github.com/bounties/)
Once https://github.com/github/securitylab-microsite/pull/151 is merged the link can point exactly at the all4one, like https://securitylab.github.com/bounties#allforone

2021-11-18 11:14 UTC, JarLob commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +description: Submit a CodeQL query for the All For One, One For All bounty (https://securitylab.github.com/bounties)
Not sure if it is visible somewhere, but once https://github.com/github/securitylab-microsite/pull/151 is merged the link can point exactly at the all4one, like https://securitylab.github.com/bounties#allforone

2021-11-18 11:14 UTC, JarLob commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +        - C#
Ruby? @xcorail I think it was commented on Slack that it is already in the bounty program....

2021-11-18 11:14 UTC, JarLob commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      description: CWE that best fits the vulnerability class modeled with your query
```suggestion
      description: [CWE](https://cwe.mitre.org/data/index.html) that best fits the vulnerability class modeled with your query
```

2021-11-18 11:41 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +description: Submit a CodeQL query for the All For One, One For All bounty (https://securitylab.github.com/bounties)
```suggestion
description: Submit a CodeQL query for the All For One, One For All bounty (https://securitylab.github.com/bounties#allforone)
```

2021-11-18 11:41 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +        Please make sure to carefully read the [bounty program description and conditions](https://securitylab.github.com/bounties/)
```suggestion
        Please make sure to carefully read the [bounty program description and conditions](https://securitylab.github.com/bounties#allforone)
```

2021-11-18 11:41 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +        Please make sure to carefully read the [bounty program description and conditions](https://securitylab.github.com/bounties/)
Thanks

2021-11-18 11:41 UTC, pwntester commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +description: Submit a CodeQL query for the All For One, One For All bounty (https://securitylab.github.com/bounties)
Thanks

2021-11-18 11:41 UTC, JarLob approved these changes

2021-12-07 16:20 UTC, intrigus-lgtm commented on .github/ISSUE_TEMPLATE/all-for-one.yml
> +      description: [CWE](https://cwe.mitre.org/data/index.html) that best fits the vulnerability class modeled with your query
```suggestion
      description: "[CWE](https://cwe.mitre.org/data/index.html) that best fits the vulnerability class modeled with your query"
```
Enclosing the description in quotes seems to fix this error:
> There is a problem with this template
>
> YAML error: (): did not find expected key while parsing a block mapping at line 55 column 7

Otherwise the YAML parser seems to think that `[CWE]` or `label: CWE` (line above) refers to some kind of mapping, I guess.

2021-12-07 16:32 UTC, pwntester commented
@xcorail Can we merge this now?

2021-12-07 17:02 UTC, merged